module DGamma.L2R16AnchorStates

import Builtin
import Prelude.Types
import Prelude.Interfaces
import Prelude.Basics
import DGamma.Calculus
import DGamma.Coeffects
import DGamma.Metatheory
import DGamma.CP3
import DGamma.L2R2SmallStates
import DGamma.L2R10OrdinalData
import Data.List
import Data.List.Elem
import Data.Nat
import Decidable.Equality

%default total
%unbound_implicits off

||| Two independent declaration keys. The owner and spare child instead use
||| smallComponent False (no provisions). These programs perform no effects.
public export
anchorComponent : Bool -> Component Bool (\key => Unit) Unit String
anchorComponent provision = MkComponent (MkCoeffectSpec [] UniqueNil)
  (MkCoeffectSpec [provision] (UniqueCons (\member => uninhabited member) UniqueNil)) []

||| Literal operation-built snapshots, NOT a recursive evaluator. Original
||| cuts 0..9 execute Begin0,Finish0,Retire1,Remove1,Retire2,Remove2,Retire3,
||| Insert4(True),Insert5(False). Alternate cuts 10..12 put Insert4 before
||| Retire3, keeping Insert5 last. Only these edges will receive certificates;
||| other Nat inputs return cut9 and assert no additional transition.
public export
anchorState : Nat -> SystemState Nat Bool (\key => Unit) Unit String
anchorState 0 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)
anchorState 1 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))
anchorState 2 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))
anchorState 3 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))
anchorState 4 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))))
anchorState 5 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))))
anchorState 6 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))))))
anchorState 7 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))))))
anchorState 8 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))))))) Refl)
anchorState 9 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))))))) Refl) Refl)
anchorState 10 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))))) Refl)
anchorState 11 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))))) Refl))
anchorState 12 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl))))))) Refl)) Refl)
anchorState _ = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (smallComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 2 (replaceBinding @{fst fixtureDictionaries} 2 (retireFiber (freshFiber (anchorComponent False) (ChildOf 0))) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (anchorComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (smallComponent False) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (emptyContext) Refl) Refl) Refl) Refl)))))))) Refl) Refl)
