#!/usr/bin/env python3
"""E3 docs-only exact-scope sync; preserve every existing Idris block/renaming."""
from pathlib import Path
import hashlib,json,re
root=Path('/Users/vyacheslavshebanov/Work/dgamma-lane2')
p=root/'research-tests/O6-L2R5-CP3-DIFF-DRAFT.md';old=p.read_text();s=old
assert '(L2R9 research sync)' not in s
s=s.replace('(L2R8 research sync)','(L2R9 research sync)',1)
rows={
'| Own-child Retire/Remove in core |':'| Own-child Retire/Remove in core | Source-aware grammar; L2R9 native providerRetirementEntries 92bb13de, resolveRetirementEntries 04cb9093, actual retirementFrameResolverSame e3a0000c | Native provider/resolver invariance CLOSED, not lifecycle replay. Three-role contract 6dbfd236 TYPE ONLY; common producer stopped at cap after2/3. Full single and R191 whole replay OPEN |',
'| Least forced set, trace-linked classifier, anchor assignment |':'| Least forced set, trace-linked classifier, anchor assignment | L2R7 correspondence; L2R8 native isElem proof scan; L2R9 unrestricted releaseOrdinalScan 163ce4b0 + exact projection link 57a92bf6 | releaseScanAgrees (including single-key) and arbitrary-located-release completeness OPEN. L2R9 A14 data fixture STOP3/3, TYPE ONLY; REPL [3]/[3] is diagnostic, not proof. Phases/anchor transport OPEN |',
'| RootInputsBeforeLifecycle replacement scope |':'| RootInputsBeforeLifecycle replacement scope | L2R9 classifyPredecessor 0544f6b3 actual source/action; rootBirthPredecessorExcluded f55de2ea under numeric external floor; local rootControlHeadExcluded c0b8c4b6 | Local/missing outcomes for arbitrary inputs are not admitted; selected-native exclusion linkage OPEN. Whole front-scan/control-head extraction and numeric floor production OPEN. ForcedRootNeverRetired retained; attachedC earlier-bundle-controls placement lift OPEN |',
'| Normalizer endpoint relation and iteration |':'| Normalizer endpoint relation and iteration | L2R6 concrete chains; L2R8 given-chain arithmetic; L2R9 selectNativeDistanceRoot dddb9483 uses ACTUAL catalog/distance and native-birth decoder. Original/restored native contiguity paths separately checked | produceAdmittedDistanceMove, D8 FROM it, normalizePhaseDistance OPEN. CoreRestorationFixture TYPE ONLY; split B4 and assembly B12 STOP3/3; inherited B3 third attempt not launched. No GeneralCoreContiguityRestored instance |'
}
lines=s.splitlines()
for start,replacement in rows.items():
 matches=[i for i,line in enumerate(lines) if line.startswith(start)];assert len(matches)==1;lines[matches[0]]=replacement
s='\n'.join(lines)+'\n'
anchor='**L2R8 PARTIAL bounded milestone:**'
assert s.count(anchor)==1
s=s.replace(anchor,'''**L2R9 current PARTIAL milestone:** **50 retained declarations in17 modules**, source boundary6dbfd236; no production changes. GENERAL checked: executable release ordinals + exact erased-enumeration projection equality; actual-source/action predecessor classifier; actual native-catalog first-positive selection with native-birth decoder; native adjacent root-birth exclusion UNDER an explicit numeric external-order floor; native provider and resolver invariance for installed retirement, including actual RetirementProviderFrame equality. These are exact kernels, NOT a normalizer/replay theorem. A14 fixture, phases, core restoration, native admitted moves, D8-from-producer, normalization, lifecycle/whole replay, scoped NF/all-premises zero-gap and cross-bundle controls remain OPEN. **Complete cure NOT SIGNABLE**, Owner Option A retained. See O6-L2R9-GRIND-SHIFT-AUDIT.md, DECLARATION-ORIGINS.md and COMPILER-LEDGER.json; separate mathematical review remains parent-owned.

**Historical L2R8 PARTIAL bounded milestone:**''',1)
start='**L2R8:** NEW shared-key extraction over '
line=next(x for x in s.splitlines() if x.startswith(start))
s=s.replace(line,'''**L2R8/L2R9 release boundary:** L2R8 shared-key extraction over native `isElem` and its quantity-0 `scanObservedReleases` are retained. L2R9 `releaseOrdinalScan` (163ce4b0) is GENERAL public-export unrestricted data; `releaseOrdinalLink` (57a92bf6) proves EXACT equality to the ordinal projection of that erased enumeration. This does NOT prove arbitrary located-release completeness or agreement with the unchanged bounded elemDec-based scan. **releaseScanAgrees, including single-key, OPEN.** L2R9 `OrdinalFixtures` is TYPE ONLY: A14 STOP3/3/full revert; old L2R8 A10 STOP3/3 remains stopped. ONE authorized REPL diagnostic evaluates both public native trail scans to **[3]**; no stuck REPL term exists, but this is not a checked fixture equation. No data-produced phaseScanOk/produceForcedRootPhases. L2R7 A8 and L2R8 A10 were not re-entered.''')
start='**L2R8 revised bounded scope:**'
line=next(x for x in s.splitlines() if x.startswith(start))
s=s.replace(line,'''**L2R9 selection/classifier scope:** `selectNativeDistanceRoot` (dddb9483) GENERALLY instantiates searchDistance/selectFirstPositiveObserved with the ACTUAL scanRootCatalog/rootDistance and supplies scanCatalogBirth; no catalog/selection/birth decoder oracle. Positive-root key-forcing identification remains separate. `classifyPredecessor` (0544f6b3) is executable for ALL8 actions with actual source lookup/parent/own Dec equations. Foreign lifecycle/insert and foreign child-control packets are authenticated; root insert/control cases and local/missing outcomes remain explicit. Excluding local/missing for the selected native predecessor is OPEN. `rootBirthPredecessorExcluded` (f55de2ea) proves native adjacency contradiction UNDER numeric externalFloor, retaining FrontNormal/NeverRetired/phase; deriving the bound from catalog max/rank is OPEN. `rootControlHeadExcluded` is LOCAL exact guard algebra, not whole-scan-to-head decoding. attachedC forced controls require earlier-placed-bundle linkage (OPEN). **Move existence, D8 FROM the producer and normalizePhaseDistance stay OPEN** under supervisor branch(A); no Insert/Insert attempt or existing-obligation weakening.''')
line=next(x for x in s.splitlines() if x.startswith('`GeneralCoreContiguityRestored` (bf888aec)'))
s=s.replace(line,'''`GeneralCoreContiguityRestored` (bf888aec) remains TYPE ONLY: exact contiguous source-aware extended-core ACTION WORD plus RegistryExtensional whole-run endpoints, not literal state-indexed core equality. L2R9 original native path5+2 and restored path3+4 are separately checked; the three-edge split path B4 STOP3/3. B3 whole17-edge assembly's inherited THIRD attempt is NOT launched. CoreRestorationFixture (3e8c5109) is precise TYPE ONLY; B12 producer STOP3/3/full revert. Snapshot equality for state recipes is not native split execution or core restoration. No general contract instance is claimed.''')
line=next(x for x in s.splitlines() if x.startswith('**Main-lane fix candidate, NOT a lane edit:**'))
s=s.replace(line,'''**L2R9 native retirement boundary:** main40d0d59e was read via git objects only; its observed-head TYPE/shape was copied with distinct lane names, not its main module. Lane `laneProviderHeadObserved` (58375d49) produces the actual guard and both native head equations without premises. `laneProviderHeadSame` (61972e01), using dependent Bool elimination (a1cb1343), avoids projected/recreated if types. `providerRetirementEntries` (92bb13de), `resolveRetirementEntries` (04cb9093), and `retirementFrameResolverSame` (e3a0000c) now GENERALLY prove native provider/resolver invariance from actual installed lookup, not view oracles. No production edit/rebuild is needed for these research proofs.

| original-edge lifecycle role | exact contract | producer |
|---|---|---|
| LBegin | NativeLifecycleRetirementRole, checked6dbfd236 | common producer reached first clause, stopped at cap after2/3 when resolver rewrite could not reach inside neutral beginFiberAction; full revert |
| LIter | same exact native checked-edge + snapshot contract | clause in common attempt source; NOT independently reached/checked |
| LFinish | same exact native checked-edge + snapshot contract | clause in common attempt source; NOT independently reached/checked |

Both D14 attempts used original checked edges + actual RetirementProviderFrame only; no supplied alternate edge. Explicit native-equality annotation did not solve original owner/lifecycle decoding. Third attempt unused; NOT a 3/3 exhaustion or semantic counterexample. The adapter to existing ForeignBeginPlanView and concrete update/snapshot commutation are next. **Full single OPEN; whole L2R2 ForeignReplay on R191 NOT RUN/OPEN.** No replay endpoint is claimed. The old L2R8 fixture TYPE comment is corrected by the exact authorized E2 patch bd28c47b, fresh V5; its producer is still OPEN.''')
s=s.replace('## Serialized seeded rebuild plan / R196 coordination','## Serialized seeded rebuild plan / main-lane coordination')
s=s.replace('Before owner-signed production change: refresh','L2R9 coordination: R198 main work ran separately; no main worktree or heavy lock/window was inspected/edited/built by this lane. Main40d0d59e TYPE evidence is the stated git-object read only; no later main completion is inferred.\n\nBefore owner-signed production change: refresh',1)
assert re.findall(r'```idris\n(.*?)```',old,re.S)==re.findall(r'```idris\n(.*?)```',s,re.S)
p.write_text(s)
p=root/'research-tests/O6-L2R5-CP3-REHOME-MANIFEST.json';m=json.loads(p.read_text());assert 'l2r9ResearchStatus' not in m
paths=sorted(str(q.relative_to(root)) for q in (root/'research-tests/O6-L2R9-Sources/DGamma').glob('*.idr'))
m['l2r9ResearchStatus']={
 'sourceBoundary':'6dbfd2360319a95ed9bb868485851d554ad0f910','status':'PARTIAL; NOT SIGNABLE as complete cure; Owner Option A/no production edits','retainedDeclarations':50,'moduleCount':17,
 'checkedKernels':['unrestricted releaseOrdinalScan and exact ordinal projection link to erased enumeration','actual source/action predecessor observation classifier (local/missing outcomes explicit)','actual native-catalog first-positive selection and native-birth decoder','native adjacent root-birth contradiction UNDER supplied numeric external floor; local front/never head algebra','original and restored native contiguity paths separately (not split/restoration)','general native provider-retirement and resolver-retirement invariance','native plus observed resolver equality from actual RetirementProviderFrame'],
 'generalProducerResidues':['releaseScanAgrees including single-key','arbitrary-located-release completeness','ordinalFixtures data agreement; phaseScanOk; produceForcedRootPhases','split native contiguity path and coreContiguityRestored / general contract instance','selected-native local/missing predecessor exclusion; numeric external-floor production; whole front/control head extraction','produceAdmittedDistanceMove; D8 from producer; normalizePhaseDistance','original-edge lifecycle replay roles; full single; R191 whole replay','origin map/filter-to-entry/native-birth linkage and converse','produceAttachedNormalForm; all-premises zero-gap; cross-bundle control placement/history'],
 'stops':{'A14':'STOP3/3 full revert; TYPE ONLY; one REPL [3]/[3] diagnostic is NOT proof','B4':'STOP3/3 split path','B12':'STOP3/3 restoration assembly','B3':'inherited third attempt NOT launched','D14':'cap STOP after2/3, third unused; contracts only; LIter/LFinish not independently reached'},
 'retainedPremise':'ForcedRootNeverRetired explicit; attachedC earlier-bundle-control lift OPEN',
 'predecessorSourceException':json.loads((root/'research-tests/O6-L2R9-COMMENT-REPAIR.json').read_text()),
 'proofSourcePaths':paths,'proofSourceSHA256':{q:hashlib.sha256((root/q).read_bytes()).hexdigest() for q in paths},
 'productionFragmentsUnchanged':True,'all30RenamingsUnchanged':True}
p.write_text(json.dumps(m,indent=2)+'\n')
print('E3: exact Tier-2 scope synced; all existing Idris blocks and old manifest keys preserved')
