#!/usr/bin/env python3
"""Adapted from run-l2r7-draft-sync.py: docs-only exact Tier-2/signature sync.
Preserves EVERY predecessor Idris code block and old manifest proof/rename
fields. Updates only the authorized draft/manifest; no Idris/compiler/git writes.
"""
import hashlib,json,pathlib,re,subprocess
ROOT=pathlib.Path('/Users/vyacheslavshebanov/Work/dgamma-lane2')
assert pathlib.Path.cwd()==ROOT
p=ROOT/'research-tests/O6-L2R5-CP3-DIFF-DRAFT.md'
s=p.read_text();before=s
assert 'L2R8 research sync' not in s
s=s.replace('(L2R7 research sync)','(L2R8 research sync)',1)
rows={
'| Own-child Retire/Remove in core |':'| Own-child Retire/Remove in core | Existing source-aware core grammar; main R197 providerHeadObserved 40d0d59e reported/read via git show only | Main head-guard proof is solved; lifecycle replay-role integration and general relocation still OPEN here; no main module imported/duplicated |',
'| Least forced set, trace-linked classifier, anchor assignment |':'| Least forced set, trace-linked classifier, anchor assignment | L2R7 general classifier correspondence retained; L2R8 sharedKeyFromAnyHit c7ba9c7e and scanObservedReleases 8d4e1894 (quantity-0, NEW isElem scan) | releaseScanAgrees with unchanged Bool scan OPEN. Executable ordinal/proof split absent; A10 data fixture3/3 stopped. phaseScanOk/produceForcedRootPhases/anchor transport OPEN |',
'| Normalizer endpoint relation and iteration |':'| Normalizer endpoint relation and iteration | L2R6 concrete native iterations retained; L2R8 searchDistance d3100a10/selectFirstPositiveObserved f3d660ee; finite-chain balance22c1f171/bound014667cb | No general native move or normalizer; D8 NOT reproduced from them. Core contract bf888aec only; B3 fixture deferred2/3 at18 GiB. Placed-prefix phase TYPE fee4c252, transport OPEN |',
'| Raw catalog and placed bundle linkage |':'| Raw catalog and placed bundle linkage | L2R7 catalog/placed-entry proofs retained; GENERAL embedRegionOccurrence00943aa6 preserves source/root-kind at offset+ordinal; observeRootOrigin d11d13c0 proves filtered-catalog ORDINAL membership | General placement, front/control exclusion, origin map/filter-to-entry/native-birth decoding and maximality converse remain OPEN. No produceAttachedNormalForm or all-premises zero-gap |'
}
lines=s.splitlines()
for prefix,row in rows.items():
 indexes=[i for i,t in enumerate(lines) if t.startswith(prefix)];assert len(indexes)==1;lines[indexes[0]]=row
s='\n'.join(lines)+'\n'
updates={
'## T2.1 Trace-linked least forced set':'''**L2R8:** NEW shared-key extraction over `isYes (isElem k keys)` observes the library decision by its OWN equation at the call site (f6a2b96d/c7ba9c7e). `scanObservedReleases` (8d4e1894) structurally constructs actual located own-child ORemove occurrences with parent and shared declared key; quantity-0 proof extraction, NOT an unrestricted runtime ordinal scan. It enumerates all releases; comparison to the old bounded scan requires filtering ordinals below the cut. **releaseScanAgrees remains NAMED OPEN and is not assumed.** A10 data-agreement fixtures exhausted3/3 and were reverted: C12/barrier agreement is NOT checked. Required next split: public-export unrestricted executable release-ORDINAL scan, linked by an equation to erased proof-carrying releases. `phaseScanOk` and `produceForcedRootPhases` remain OPEN. L2R7 A8 is not re-entered.''',
'## T2.2 Last-release/anchor assignment (key roots and barriers)':'''**L2R8:** proof-carrying isElem releases do not discharge old `anchorOf`/last-release/phase statements without `releaseScanAgrees`. `originMaximumMember` (2fe6b449) proves authentic maximum membership using observed comparisons; this is not anchor identity/ordinal transport, maximal release selection, or a phase producer.''',
'## T2.3 Front-normal form, including non-insert root orchestration':'''**L2R8:** `rootOriginCatalogOrdinal` (90392707) and unrestricted single-constructor `observeRootOrigin` (d11d13c0) prove a successful UNCHANGED origin scan is a member of its exact filtered-catalog ORDINAL list. Inverting map/filter to the actual catalog ENTRY, decoding the equality decision into root identity, then applying scanCatalogBirth and proving the reverse/maximality direction remain OPEN. This is not the full rootOriginAt ↔ native-birth linkage or front/control exclusion. Same-bundle controls retain the L2R7 scope; cross-bundle authenticated prefix/generation history remains OPEN.''',
'## T2.4 Bundle-placement linkage and selector projection':'''**L2R8 checked connector:** `embedRegionOccurrence` (00943aa6) GENERALLY embeds any native region occurrence using its actual prefix/region/suffix decomposition. It produces offset + local ordinal, the SAME native source, and transports RootOrchestrationStep including Retire/Remove. No coverage/decoder oracle is supplied. This closes the generic physical region-embedding kernel, NOT arbitrary decomposition, generation-origin linkage, front/control exclusion, PlacedBundle production, or produceAttachedNormalForm. **No all-premises-produced zero-gap application exists**, for either original attached fixture or controlFixture/attachedC. Old fixture NF/gap0 is not reused as a producer.''',
'## Iteration type/measure status':'''**L2R8 revised bounded scope:** `searchDistance` (d3100a10) is a GENERAL unrestricted first-positive list producer with exact decomposition and every earlier distance zero; `selectFirstPositiveObserved` (f3d660ee) decodes a positive-total observed search. Native catalog instantiation/key-forcing identification, predecessor admissibility, one-step square, anchor/other-root distance transport, produceAdmittedDistanceMove and D8 reproduction FROM it remain OPEN. No native Insert/Insert applicability attempt or alternate-prefix move reproduction was made.\n\n`GeneralCoreContiguityRestored` (bf888aec) is TYPE ONLY: same-origin native runs with a foreign root moved before an authentic core must produce a contiguous source-aware extended core with the exact ACTION WORD restored, plus RegistryExtensional whole-run endpoints. Literal state-indexed core equality is impossible and NOT the intended statement. B3's 17-equation native fixture producer was deferred2/3 after two light RSS stops (~18.05 GiB sampled); no checked crossing/restoration fixture exists.\n\n`iterationDistanceBalance` (22c1f171), `iterationStepsAtZero` (0b564942), and `iterationLengthBound` (014667cb) prove arithmetic of a GIVEN finite native chain. They are **not normalization; move/phase producers open**. `PlacedPrefixPhaseInvariant` (fee4c252) is TYPE ONLY: earlier forced roots have phases, genuine placed bundles and zero distance; selected root has a phase; later-root contiguity is deliberately not required mid-round. Its producers/transport and outer-round restoration are OPEN. No accessibility normalizer or callback/oracle substitute was introduced.'''
}
for heading,text in updates.items():assert s.count(heading)==1;s=s.replace(heading,heading+'\n\n'+text,1)
heading='# Tier 2 — partially checked connectors; remaining specification clauses'
intro='''**L2R8 PARTIAL bounded milestone:** 37 retained declarations in12 research modules at source boundary d11d13c0. New checked kernels are shared-key/native release proof extraction over a NEW isElem scan, ordered positive-distance search, finite-chain distance arithmetic, general physical region embedding, and origin-scan ordinal membership. General phases/moves/iteration/NF and all-premises zero-gap remain OPEN. The draft is **NOT SIGNABLE for a complete attached-grammar + placement cure until the GENERAL normalizer iteration AND cross-bundle controls close**, along with the listed connectors. No global Tier-2 row is promoted wholesale. Sources/receipts: O6-L2R8-DECLARATION-ORIGINS.md, O6-L2R8-GRIND-SHIFT-AUDIT.md and O6-L2R8-COMPILER-LEDGER.json. Earlier L2R7 paragraphs below are historical backing, not contrary current producer claims.\n\n'''
s=s.replace(heading+'\n\n',heading+'\n\n'+intro,1)
assert re.findall(r'```idris\n(.*?)```',s,re.S)==re.findall(r'```idris\n(.*?)```',before,re.S)
p.write_text(s)
p=ROOT/'research-tests/O6-L2R5-CP3-REHOME-MANIFEST.json';d=json.loads(p.read_text())
d['l2r8ResearchStatus']={'sourceBoundary':'d11d13c0','status':'PARTIAL; NOT SIGNABLE as complete attached grammar + placement cure','retainedDeclarations':37,'moduleCount':12,'generalProducerResidues':['releaseScanAgrees','executable release-ordinal/proof split','phaseScanOk','produceForcedRootPhases','coreContiguityRestored proof/fixture','produceAdmittedDistanceMove','normalizePhaseDistance','D8 reproduction from general producers','origin map/filter-to-entry/native-birth linkage and converse','front/control exclusion','produceAttachedNormalForm','all-premises zero-gap for attached/attachedC','cross-bundle authenticated prefix/generation history'],'checkedKernels':['quantity-0 shared-key and located native isElem release scan','unrestricted ordered first-positive distance scan and observed positive-total decoder','given finite-iteration distance balance, terminal-zero count and bound','generic native physical region embedding with source/root-kind transport','unrestricted unchanged origin observation with filtered-catalog ordinal membership'],'proofSourcePaths':[str(p.relative_to(ROOT)) for p in sorted((ROOT/'research-tests/O6-L2R8-Sources/DGamma').glob('*.idr'))]}
p.write_text(json.dumps(d,indent=2)+'\n')
print('Docs-only L2R8 sync; ALL predecessor Idris fragments preserved')
