#!/usr/bin/env python3
"""Docs-only L2R7 sync, adapted from run-l2r6-draft-sync.py.
Preserves every existing Tier-1 code fragment, all30 applied renamings and CP3.
Adds only checked research status and an explicitly same-bundle C candidate.
No compiler/cache/staging/shared-window or main-worktree operation.
"""
import ast, hashlib, json, pathlib, subprocess
ROOT=pathlib.Path('/Users/vyacheslavshebanov/Work/dgamma-lane2')
BASE='87e9fb20'
assert pathlib.Path.cwd()==ROOT

def original(path): return subprocess.check_output(['git','show',BASE+':'+path],cwd=ROOT,text=True)
def sha(data): return hashlib.sha256(data).hexdigest()
p='research-tests/O6-L2R5-CP3-DIFF-DRAFT.md';draft=original(p)
manifestpath='research-tests/O6-L2R5-CP3-REHOME-MANIFEST.json';manifest=json.loads(original(manifestpath))
draft=draft.replace('(L2R6 research sync)','(L2R7 research sync)')
rows={
'| Least forced set, trace-linked classifier, anchor assignment |':'| Least forced set, trace-linked classifier, anchor assignment | L2R7 classifyForcedSound 190703a3 / classifyForcedComplete e353c4cc / observeForcedClassification 52a22cb3; both general-correspondence fixtures 54545866; inherited least closure/anchorAssignment | GENERAL classifier correspondence and original-output membership CLOSED. Decoded release/shared-key/parent scan witness, general phases and anchorTransport OPEN (A8 3/3 stop); anchor contract 99c3a794 and actual admitted-move instance 4db206f1 |',
'| RootInputsBeforeLifecycle replacement scope |':'| RootInputsBeforeLifecycle replacement scope | Inherited FrontNormal/NeverRetired scans; NEW same-bundle attachedC grammar a79d8557/b3746a68, sound inclusions f5fe40c5/60130345, native controls fixture 28c7cc15 | Forced controls IN the bundle on the fixture, gap0. Earlier-bundle controls need authenticated prefix/generation history (OPEN); origin correspondence and general scoped NF OPEN |',
'| Raw catalog and placed bundle linkage |':'| Raw catalog and placed bundle linkage | GENERAL scanCatalogBirth 8d579501 + locatedBirthBound 94273eaa; placedCatalogCoverage fabb56e1 / placedRootCoverage 8c3b1141; fresh decoded R/R/S fixture occurrences c390795b | Catalog→actual ordinal birth→placed bundle occurrence CLOSED. General PlacedBundle producer, all-root-control exclusion, region embedding and scoped AttachedNormalForm producer remain OPEN (exact TYPE 435bd364) |',
'| Normalizer endpoint relation and iteration |':'| Normalizer endpoint relation and iteration | L2R6 native 1→0/2→1→0 instances and RegistryExtensional endpoint theorem retained; L2R7 actual anchor transport fixture 4db206f1 | General phase/move/iteration producers and D8 reproduction from them NOT CLOSED. All-roots contiguous-core phase preservation has a candidate obstruction; placed-prefix/selected-root invariant repair plus coreContiguityRestored OPEN. L2R6 types unchanged |',
'| O19 safetyBlocksAdjacent over full attached blocks |':'| O19 safetyBlocksAdjacent over full attached blocks | L2R4 original fixtures; L2R7 controls fixture physical gap0 28c7cc15; conditional attachedCZeroGapInNormalForm cbc6d783 | GENERAL scoped NF/all-premises-produced selector zero-gap OPEN, for attached and attachedC. New conditional theorem retains coverage/NF/universal separation; no premise generated by fiat |'}
for prefix,new in rows.items():
 lines=draft.splitlines();matches=[i for i,l in enumerate(lines) if l.startswith(prefix)];assert len(matches)==1
 lines[matches[0]]=new;draft='\n'.join(lines)+'\n'
a=draft.index('**NOT YET SIGNABLE AS A COMPLETE CURE.** L2R6 checked');b=draft.index('\n## T2.1',a)
draft=draft[:a]+'''**NOT YET SIGNABLE AS A COMPLETE CURE.** L2R7 is an explicitly PARTIAL bounded research milestone. General classifier correspondence and generated catalog→actual placed occurrence producers now close, as does the new SAME-BUNDLE controls grammar/fixture and its conditional zero-gap theorem. General phases, admitted-move existence, accessibility iteration, global placement and scoped NF/all-premises zero-gap do NOT close. No global connector row below is promoted wholesale to Tier 1. Older API fragments remain **L2R5 proposed API TEXT**, not compiled production signatures.

Exact code/check/commit provenance: `O6-L2R7-DECLARATION-ORIGINS.md`, `O6-L2R7-MICRO-UNIT-LEDGER.json`, `O6-L2R7-GRIND-SHIFT-AUDIT.md`. All new sources are in `O6-L2R7-Sources/DGamma/`. L2R1–L2R6 proof sources and production CP3 are untouched. The L2R6 ratified milestone and reviewer ACCEPT-WITH-NOTES are recorded in the new audit.
''' + draft[b:]
old='GENERAL soundness/completeness against the inductive relation remains OPEN.'
assert old in draft;draft=draft.replace(old,'GENERAL soundness/completeness against this independent inductive relation now CLOSES in L2R7 (190703a3/e353c4cc), with executable original-output membership and both directions in observeForcedClassification (52a22cb3). classifierCorrespondenceFixtures (54545866) applies the general proof to the key-root and barrier fixtures; no scalar Refl over nested fixture builders.')
heading='## T2.1 Trace-linked least forced set'
draft=draft.replace(heading,heading+'''

**L2R7 checked extension:** scanCatalogBirth (8d579501) GENERALLY decodes membership of the actual computed catalog into a native LocatedActionOccurrence with exact offset/ordinal. locatedBirthBound (94273eaa) proves its strict interval bound. This is catalog decoding, NOT the missing shared-key release-scan decoder. A8 elemDecConsObserved exhausted3/3 and was fully reverted; that observed-Dec/library-case wall is not re-entered. `SharedKey` is a TYPE, not an extracted release witness. General `phaseScanOk` / `produceForcedRootPhases` remain OPEN/no implementation.
''')
heading='## T2.2 Last-release/anchor assignment (key roots and barriers)'
draft=draft.replace(heading,heading+'''

**L2R7 transport ruling:** do NOT assert literal current-cut `anchorOf` equality for every root. If moving R crosses a foreign own-child Remove whose key is shared by later S, that release's physical cut shifts right. `adjacentOrdinalMap` (2d0db779) maps the crossed action +1, the moved root -1, others unchanged. `AnchorTransport` (99c3a794) is a precise per-root CONTRACT with authentic catalog root/key-seed identities, native admitted move, mapped located own-child removals on both traces, parent/shared-key witnesses, exact last-release/anchor equations, and `afterAnchor = S (adjacentOrdinalMap cut (pred beforeAnchor))`. `anchorTransportFixture` (4db206f1) inhabits it for the real R-over-Begin2 step (release3 fixed, anchor4→4). GENERAL anchorTransport and other-root distance invariance remain OPEN; the fixture is not the shifting-S example or a general proof.
''')
a=draft.index('**Disposition is NOT chosen by fiat.**');b=draft.index('\n`ForcedRootPhase`',a)
draft=draft[:a]+'''**FORCED-ROOT CONTROL DISPOSITION = option (1) RICHER BUNDLE WITH CONTROLS — the forced-root bundle admits, in orchestration order, ORetire/ORemove of a root already inserted in this or an earlier bundle (elements: OInsert root with release/barrier witness | ORetire root with an already-bundled witness | ORemove root likewise); the attached block's body = core ++ bundle-with-controls; the gap statement is unchanged.**

**Explicit bounded implementation ruling:** L2R7 implements SAME-BUNDLE controls only. OrderedForcedRootBundleC threads locally consumed roots; controls require Elem plus actual source lookup and Root parent; ActorLifecycleOnlyAttachedC starts with EMPTY history. Cross-bundle controls remain OPEN under the **authenticated prefix/generation history** connector. Accepting arbitrary priorRoots for earlier bundles would be history by fiat and unsafe under raw-name reuse. The original L2R3 grammar is untouched. The original L2R6 FrontNormal/NeverRetired statements are NOT changed.

`ForcedRootControlInBundle` (e6e75654) is inhabited by `controlFixture` (28c7cc15): ten native one-origin edges, parent0 [0,8), actor2 [8,10), gap0; R,S,Retire3,Remove3 are INSIDE the ordered bundle. `bundleIntoC`/`attachedIntoC` (f5fe40c5/60130345) are sound forward inclusions. Full located/order C records retain installedness, episode uniqueness, activity and physical decomposition. `attachedCZeroGapInNormalForm` (cbc6d783) is PROVED conditionally with the exact old coverage/NF/universal-separation obligations. Its GENERAL premise producers are not supplied.

The old `ForcedRootRetireInBlock` remains TYPE ONLY and still asks for the nonexistent post-whole-bundle interval in the old grammar; it is not silently repaired or inhabited by the different C predicate.
''' +draft[b:]
draft=draft.replace('The grammar has no constructor attaching root Retire/Remove to a trailing insertion bundle. The exact disposition of forced-root controls is still an owner/research obligation; this draft does not settle it by an over-strong universal front clause.','The unchanged L2R3 grammar has no such constructor. The NEW C candidate admits same-bundle controls; cross-bundle origin authentication and the general front/control occurrence theorem remain OPEN. No over-strong universal front clause is imposed.')
a=draft.index('**PARTIALLY CHECKED — L2R6Anchors/PlacementFixtures.**');b=draft.index('\n\nDo not redefine RootInputsBeforeLifecycle',a)
draft=draft[:a]+'''**PARTIALLY CHECKED — GENERAL PER-ENTRY CONNECTOR NOW CLOSED.** L2R6 PlacedBundle (77fcf3a6) supplies complete same-anchor catalog equality to one actual original bundle. L2R7 `placedCatalogCoverage` (fabb56e1) turns that equality and computed membership into a FULL AttachedBundleOccurrence at the actual global ordinal, using the general native catalog decoder and strict interval bound. `placedRootCoverage` (8c3b1141) additionally produces filtered membership from a genuine global catalog member and explicit observed accepted anchor match. Neither takes a rootInBundle callback. `placedCoverageFixtures` (c390795b) applies the general theorem to both full original fixtures, constructing fresh R/R/S occurrences at4/4/5 rather than reusing fixture NF.

**Still OPEN:** general PlacedBundle production; decoding every relevant gap root's origin/anchor, excluding root Retire/Remove from the interim NeverRetired gap scope, and authenticating region embedding. `GeneralAttachedNormalForm` (435bd364) is the precise TYPE over actual BlockBeforeAttached gaps + FrontNormal + NeverRetired + all genuine phases + actual placements; `produceAttachedNormalForm` is OPEN/no implementation. No all-premises-produced zero-gap theorem closes (attached or attachedC). Existing fixture empty-gap NF is not promoted to the general producer.
''' +draft[b:]
heading='## Iteration type/measure status'
draft=draft.replace(heading,heading+'''

**L2R7 boundary:** `produceForcedRootPhases`, `produceAdmittedDistanceMove`, `normalizePhaseDistance` and reproduction of L2R6 D8 FROM those general theorems do NOT close. The release decoder stopped at A8. No native Insert/Insert applicability proof was produced. Additional candidate obstruction (NOT a checked counterexample): moving R through foreign actor B's extended core temporarily splits B's lifecycle→release interval, so the old all-roots contiguous ForcedRootPhase invariant may fail mid-iteration. Supervisor direction, NOT a proof: keep phases for placed prefix + selected root, restore remaining phases after the outer step. Named OPEN `coreContiguityRestored` must prove the foreign core is byte-identical once R exits it. L2R6 obligation types are untouched; the different invariant is not silently substituted into them.
''')
sourcepath='research-tests/O6-L2R7-Sources/DGamma/L2R7AttachedC.idr';source=(ROOT/sourcepath).read_text()
a=source.index('public export\ndata OrderedForcedRootBundleC');b=source.index('||| Sound forward inclusion',a);fragment=source[a:b].rstrip()+'\n'
candidate='''### T1.C — NEW same-bundle controls candidate (research syntax, not a production patch)

Fully checked at its authorized SAME-BUNDLE scope. This is exact new research syntax; old Tier-1 fragments remain byte-identical and L2R3 is untouched. Cross-bundle prefix/generation history is Tier-2 debt, so this is NOT the full original richer-control ruling. No production renamings have been applied to this fragment. Sources/inclusions: L2R7AttachedC, a79d8557/b3746a68/f5fe40c5/60130345. Native fixture 28c7cc15 and conditional lifted zero-gap cbc6d783 are checked backing, not global normalizer/selector claims.

```idris
'''+fragment+'```\n\n---\n\n'
draft=draft.replace('# Tier 2 — partially checked connectors; remaining specification clauses',candidate+'# Tier 2 — partially checked connectors; remaining specification clauses',1)
manifest['l2r7SameBundleControlsCandidate']=dict(status='checked research same-bundle candidate only; cross-bundle connector OPEN; not production rehome',source=sourcepath,sourceSHA256=sha(source.encode()),fragmentSHA256=sha(fragment.encode()),appliedProductionRenamings=False,fixtureCommit='28c7cc15',conditionalZeroGapCommit='cbc6d783')
manifest['l2r7ResearchStatus']=dict(classifierCorrespondence='GENERAL checked',catalogLocatedBirth='GENERAL checked',placedCatalogOccurrence='GENERAL checked',releaseScanSharedKeyDecoder='OPEN: A8 3/3 fully reverted',generalPhaseMoveIteration='OPEN',generalScopedNF='TYPE ONLY; producer OPEN',allPremisesZeroGap='OPEN',predecessorProofSourcesUntouched=True)
for section in manifest['tier1Sections']:
 text=draft.split('### '+section['title']+'\n\n```idris\n',1)[1].split('```',1)[0]
 assert sha(text.encode())==section['sha256'],section['title']
for path,h in manifest['checkedSourceSHA256'].items():assert sha((ROOT/path).read_bytes())==h
assert manifest['renamings']==json.loads(original(manifestpath))['renamings']
assert (ROOT/'research-tests/run-l2r5-draft.py').read_text()==original('research-tests/run-l2r5-draft.py')
(ROOT/p).write_text(draft);(ROOT/manifestpath).write_text(json.dumps(manifest,indent=2)+'\n')
print('L2R7 draft sync PASS: original Tier1 fragments and30 mappings unchanged; same-bundle candidate and exact partial status added')
