module DGamma.L2R17SanctionedStates

import Builtin
import Prelude.Types
import Prelude.Interfaces
import Prelude.Basics
import Prelude.EqOrd
import DGamma.Calculus
import DGamma.Coeffects
import DGamma.Metatheory
import DGamma.CP3
import DGamma.CP5AvailabilityAwarePlacement
import DGamma.CP5UniqueRawNameInsertions
import DGamma.L2R2SmallStates
import DGamma.L2R3ForcedClosure
import DGamma.L2R5RootCatalog
import DGamma.L2R6ForcedScan
import DGamma.L2R6Anchors
import DGamma.L2R10OrdinalData
import DGamma.L2R16AnchorStates
import DGamma.L2R16AnchorNative
import DGamma.L2R16AnchorTrace
import DGamma.L2R16AnchorTrail
import DGamma.L2R16ProductionBridge
import Data.DPair
import Data.Bool
import Data.List
import Data.List.Elem
import Data.Maybe
import Data.Nat
import Decidable.Equality
import Decidable.Equality.Core
import Decidable.Decidable

%default total
%unbound_implicits off

||| Supervisor-authorized DIFFERENT data construction after exhausted X5.
||| Literal operation-built snapshots, never runNative/twinsSegment results.
||| Source cuts0..10, reversed cuts0,11..20. Programs have no effects.
public export
sanctionedState : Nat -> SystemState Nat Bool (\key => Unit) Unit String
sanctionedState 0 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)
sanctionedState 1 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))
sanctionedState 2 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)))
sanctionedState 3 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))
sanctionedState 4 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)))))
sanctionedState 5 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)
sanctionedState 6 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))
sanctionedState 7 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)))
sanctionedState 8 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))))
sanctionedState 9 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)))))
sanctionedState 10 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))))) Refl)
sanctionedState 11 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))
sanctionedState 12 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)))
sanctionedState 13 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))
sanctionedState 14 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)))))
sanctionedState 15 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)
sanctionedState 16 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))
sanctionedState 17 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)))
sanctionedState 18 = MkSystemState ()
  (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))))
sanctionedState 19 = MkSystemState ()
  (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl)))))
sanctionedState 20 = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 4 (freshFiber (anchorComponent True) Root) (deleteBinding @{fst fixtureDictionaries} 1 (replaceBinding @{fst fixtureDictionaries} 1 (retireFiber (freshFiber (anchorComponent True) (ChildOf 0))) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 0 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 5 (freshFiber (anchorComponent False) Root) (deleteBinding @{fst fixtureDictionaries} 3 (replaceBinding @{fst fixtureDictionaries} 3 (retireFiber (freshFiber (anchorComponent False) (ChildOf 2))) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Active id EmptyView)) (replaceBinding @{fst fixtureDictionaries} 2 (setFiberLifecycle (freshFiber (smallComponent False) Root) (Reloading [] id EmptyView)) (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl))))) Refl))))) Refl)
sanctionedState _ = MkSystemState ()
  (insertBinding @{fst fixtureDictionaries} 1 (freshFiber (anchorComponent True) (ChildOf 0)) (insertBinding @{fst fixtureDictionaries} 3 (freshFiber (anchorComponent False) (ChildOf 2)) (insertBinding @{fst fixtureDictionaries} 0 (freshFiber (smallComponent False) Root) (insertBinding @{fst fixtureDictionaries} 2 (freshFiber (smallComponent False) Root) emptyContext Refl) Refl) Refl) Refl)
