module DGamma.L2R3SmallAttached

import DGamma.Calculus
import DGamma.Coeffects
import DGamma.Metatheory
import DGamma.CP3
import DGamma.CP5ActorLifecycleOnlyExtended
import DGamma.L2R2SmallStates
import DGamma.L2R2SmallExecution
import DGamma.L2R3Attached
import DGamma.L2R3AttachedGap
import Data.Nat
import Data.List.Elem
import Decidable.Equality

%default total
%unbound_implicits off

||| Native Remove1 at body ordinal2 releases True for Root3. The occurrence
||| is in the SAME Finish0/Retire1/Remove1 core used by the attached fixture.
public export
0 smallRelease : DGamma.L2R3Attached.AttachedRelease Nat Bool Unit String (\key => Unit) %search 0
  (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions))) (smallComponent True)
smallRelease = DGamma.L2R3Attached.MkAttachedRelease 1 (retireFiber (freshFiber (smallComponent True) (ChildOf 0)))
  (MkLocatedActionOccurrence (smallState 3) (smallState 4) (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) NoTransitions)) (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions Refl Refl) Refl Refl True Here Here

||| C12 counterpart of L2R2SmallBlocks:23 on the unchanged smallTrace.
||| Parent range includes Root3, actor2 starts immediately after its bundle.
public export
record SmallAttachedBlocks where
  constructor MkSmallAttachedBlocks
  freeingBlock : LocatedOpenEpisodeBlockAttached Nat Bool Unit String (\key => Unit) %search %search 0 smallTrace
  followingBlock : LocatedOpenEpisodeBlockAttached Nat Bool Unit String (\key => Unit) %search %search 2 smallTrace
  physicalOrder : BlockBeforeAttached Nat Bool Unit String (\key => Unit) %search %search smallTrace 0 2 freeingBlock followingBlock
  0 freeingRange : (transitionCount (attachedBefore freeingBlock),
    transitionCount (attachedBefore freeingBlock) + S (transitionCount (attachedBody freeingBlock))) = (0, 5)
  0 followingRange : (transitionCount (attachedBefore followingBlock),
    transitionCount (attachedBefore followingBlock) + S (transitionCount (attachedBody followingBlock))) = (5, 7)
  0 forcedRootGapCount : transitionCount (attachedBetweenBlocks physicalOrder) = 0
  0 forcedRootInBody : LocatedActionOccurrence (OInsert 3 Root (smallComponent True)) (attachedBody freeingBlock)

||| Simultaneous native construction, not a scalar observer over old blocks.
||| Parent0 [0,5) includes Retire1, Remove1 and release-justified Insert3;
||| actor2 [5,7). The literal gap is NoTransitions in the SAME smallTrace.
public export
0 smallAttachedBlocks : SmallAttachedBlocks
smallAttachedBlocks = MkSmallAttachedBlocks
  (MkLocatedOpenEpisodeBlockAttached (smallState 0) (smallState 1) (smallState 5)
    NoTransitions (MkBeginStep (smallBegin0 smallNativeExecution))
    (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions))))
    (InstalledStep {first = smallState 1} {middle = smallState 2} {finalState = smallState 5} (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions))) Refl (InstalledStep {first = smallState 2} {middle = smallState 3} {finalState = smallState 5} (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions)) Refl (InstalledStep {first = smallState 3} {middle = smallState 4} {finalState = smallState 5} (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions) Refl (InstalledStep {first = smallState 4} {middle = smallState 5} {finalState = smallState 5} (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution) NoTransitions Refl (InstalledEnd Refl)))))
    (AttachedWithRoots (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions))) (ExtendedLifecycleStep (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions)) Refl Refl (ExtendedChildRetireStep (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions) 1 (freshFiber (smallComponent True) (ChildOf 0)) Refl Refl Refl (ExtendedChildRemoveStep (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions 1 (retireFiber (freshFiber (smallComponent True) (ChildOf 0))) Refl Refl Refl ExtendedLifecycleEnd))) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions) (ForcedBundleStep 3 (smallComponent True) (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions Refl (DGamma.L2R3Attached.KeyReleased smallRelease) DGamma.L2R3Attached.ForcedBundleEnd))
    (MoreTransitions (Fired {before = smallState 5} {afterState = smallState 6} %search %search (LBegin 2) LBeginTag (smallBegin2 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions))
    NoLifecycleByEnd (NoLifecycleByStep (Fired {before = smallState 5} {afterState = smallState 6} %search %search (LBegin 2) LBeginTag (smallBegin2 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions) (\life, same => case same of Refl impossible) (NoLifecycleByStep (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions (\life, same => case same of Refl impossible) NoLifecycleByEnd)) Refl Refl)
  (MkLocatedOpenEpisodeBlockAttached (smallState 5) (smallState 6) (smallState 7)
    (MoreTransitions (Fired {before = smallState 0} {afterState = smallState 1} %search %search (LBegin 0) LBeginTag (smallBegin0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions))))) (MkBeginStep (smallBegin2 smallNativeExecution))
    (MoreTransitions (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions)
    (InstalledStep {first = smallState 6} {middle = smallState 7} {finalState = smallState 7} (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution) NoTransitions Refl (InstalledEnd Refl))
    (AttachedWithoutRoots (MoreTransitions (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions) (ExtendedLifecycleStep (Fired {before = smallState 6} {afterState = smallState 7} %search %search (LAdvance 2) LFinishTag (smallFinish2 smallNativeExecution)) NoTransitions Refl Refl ExtendedLifecycleEnd))
    NoTransitions
    (NoLifecycleByStep (Fired {before = smallState 0} {afterState = smallState 1} %search %search (LBegin 0) LBeginTag (smallBegin0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions)))) (\life, same => case same of Refl impossible) (NoLifecycleByStep (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions))) (\life, same => case same of Refl impossible) (NoLifecycleByStep (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions)) (\life, same => case same of Refl impossible) (NoLifecycleByStep (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions) (\life, same => case same of Refl impossible) (NoLifecycleByStep (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions (\life, same => case same of Refl impossible) NoLifecycleByEnd))))) NoLifecycleByEnd Refl Refl)
  (MkBlockBeforeAttached NoTransitions Refl)
  Refl Refl Refl
  (MkLocatedActionOccurrence (smallState 4) (smallState 5) (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions))) (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions Refl Refl)

||| Nonvacuous instance of the generic membership record: Root3 really lies
||| in parent0's trailing bundle at global ordinal4, with exact local bounds.
public export
0 smallInsertedBundleMember : DGamma.L2R3AttachedGap.AttachedBundleOccurrence Nat Bool Unit String (\key => Unit)
  %search %search smallTrace (OInsert 3 Root (smallComponent True)) 4
smallInsertedBundleMember = DGamma.L2R3AttachedGap.MkAttachedBundleOccurrence 0 (freeingBlock smallAttachedBlocks)
  (smallState 4) (MoreTransitions (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions))) (ExtendedLifecycleStep (Fired {before = smallState 1} {afterState = smallState 2} %search %search (LAdvance 0) LFinishTag (smallFinish0 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions)) Refl Refl (ExtendedChildRetireStep (Fired {before = smallState 2} {afterState = smallState 3} %search %search (ORetire 1) ORetireTag (smallRetire1 smallNativeExecution)) (MoreTransitions (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions) 1 (freshFiber (smallComponent True) (ChildOf 0)) Refl Refl Refl (ExtendedChildRemoveStep (Fired {before = smallState 3} {afterState = smallState 4} %search %search (ORemove 1) ORemoveTag (smallRemove1 smallNativeExecution)) NoTransitions 1 (retireFiber (freshFiber (smallComponent True) (ChildOf 0))) Refl Refl Refl ExtendedLifecycleEnd)))
  (MoreTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions) (ForcedBundleStep 3 (smallComponent True) (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions Refl (DGamma.L2R3Attached.KeyReleased smallRelease) DGamma.L2R3Attached.ForcedBundleEnd) Refl
  (MkLocatedActionOccurrence (smallState 4) (smallState 5) NoTransitions (Fired {before = smallState 4} {afterState = smallState 5} %search %search (OInsert 3 Root (smallComponent True)) OInsertTag (smallInsert3 smallNativeExecution)) NoTransitions Refl Refl) 4 Refl Refl (LTESucc (LTESucc (LTESucc (LTESucc LTEZero)))) (LTESucc (LTESucc (LTESucc (LTESucc (LTESucc LTEZero)))))
